#!/usr/bin/env bash
# displays Best School 10 times.

count=1
while [ $count -le 100 ]
do
    if [ $((count%15)) = 0 ]
    then
        echo "FizzBuzz"
    elif [ $((count%3)) = 0 ]
    then
        echo "Fizz"
    elif [ $((count%5)) = 0 ]
    then
        echo "Buzz"
    else
        echo "$count"
    fi
    count=$((count+1))
done
